### ISSUE TITLE
Comfort Range set back to 3 on reboot

### ISSUE THREAD

**Issue by raycekar** [HestiaPi/hestia-touch-openhab#63] opened 2020-12-16 04:55 UTC
Running v1.2-Dev and I found after a reboot that when set to eco mode, the comfort Range is not persistent.  I usually like mine at 4 degrees :)

**Comment by gulliverrr** [comment] 2020-12-16 06:25
Hmmm... will look into that. The Comfort_Value Item (under Settings labelled "Comfort Range") needs to be stored in persistent storage.

**Comment by gulliverrr** [comment] 2020-12-16 06:27
Duplicate of #62

**Closed as completed by gulliverrr** 2020-12-16 06:27 UTC
Labels: enhancement
