### ISSUE TITLE
Hestia Pi boot problem

### ISSUE THREAD

**Issue by mazingaz87** [HestiaPi/hestia-touch-openhab#66] opened 2021-12-11 09:39 UTC
Good morning guys. I am new to the forum and forgive me if I cannot write well in English. I bought the Hestia kit and assembled everything perfectly (I hope). Later I wrote the image on the micro sd. Initially everything worked until the reboot. After restarted it no longer works from app. But the most interesting thing that I cannot understand is why if I enter openhub and manually turn on the heating relay it returns to work. I understand that there is something wrong with the basic gui implementation. I tried to rewrite the sd card but still the same problem. Can you help me? the project is right and I would like to carry it out. thank you

**Comment by gulliverrr** [comment] 2021-12-14 06:51
Closing as duplicate of https://community.hestiapi.com/t/hestia-pi-problem/1887

**Closed as completed by gulliverrr** 2021-12-14 06:51 UTC
